Unterlagen API scopes Beschreibung aktualisiert
europace/authorization-api pull request #28
Opened 2020-09-18 07:22 UTC by konfusio

## Motivation
wir haben in der https://github.com/europace/unterlagen-api den scopes noch mal eine Beschreibung gegeben die auch von Bianca abgenommen wurde.
Diese soll nun auch hier verwendet werden

2020-09-18 07:30 UTC, sgrell approved these changes
Mir ist ehrlich gesagt gar nicht klar, wo man diese Beschreibung einsehen kann.

2020-09-18 07:31 UTC, schmidthappens requested changes

2020-09-18 07:31 UTC, schmidthappens commented on europace_security.yaml
> +        als Vertrieb, Abruf der Metadaten und des Inhalts hochgeladener Dokumente.
Warum habt ihr denn hier nun keinen Satzanfang mehr drin?

2020-09-18 07:31 UTC, schmidthappens commented on europace_security.yaml
> +        als Vertrieb, Hochladen von Dokumenten und Anstoßen der Kategorisierung. Die Kategorisierung muß angestoßen werden, damit nachfolgend die erkannten Unterlagen (kategorisierter Inhalt) freigeg
muß  -> muss

2020-09-18 07:31 UTC, schmidthappens commented on europace_security.yaml
> +        als Vertrieb, Hochladen von Dokumenten und Anstoßen der Kategorisierung. Die Kategorisierung muß angestoßen werden, damit nachfolgend die erkannten Unterlagen (kategorisierter Inhalt) freigeg
> Weiterhin das Aktualisieren der Metadaten und Löschen hochgeladener Dokumente.
Das ist kein Satz, da fehlt ein Verb ;)

2020-10-30 08:57 UTC, ollio approved these changes
Syntaktisch sehe ich keine Probleme

2021-03-12 11:11 UTC, closed without merging